# Generated by Django 5.1.6 on 2025-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_gene_guard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CholesterolResult',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('responses', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
