# Generated by Django 5.1.6 on 2025-05-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_gene_guard', '0002_cholesterolresult'),
        ('form_gene_guard', '0002_userprofile'),
    ]

    operations = [
    ]
