# Generated by Django 5.1.6 on 2025-05-15 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_gene_guard', '0003_merge_0002_cholesterolresult_0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reponses_Sickle_Cell_Anemia',
        ),
        migrations.AddField(
            model_name='cholesterolresult',
            name='user_profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_gene_guard.userprofile'),
        ),
        migrations.AddField(
            model_name='sicklecellresult',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sickle_results', to='form_gene_guard.userprofile'),
        ),
    ]
