# Generated by Django 5.1.6 on 2025-05-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_gene_guard', '0004_delete_reponses_sickle_cell_anemia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
