# Generated by Django 6.0 on 2025-12-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_gene_guard', '0006_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioResult',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_gene_guard.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DiabetesResult',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_gene_guard.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GalactosemiaResult',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('responses', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_gene_guard.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralResult',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_symptoms', models.JSONField()),
                ('predicted_diseases', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_gene_guard.userprofile')),
            ],
        ),
    ]
